### ISSUE TITLE
Crédito

### ISSUE THREAD

**Issue by h4murabi** [hamurabiaraujo/sisbank#1]
- Solicita um número e valor
- Atualiza a conta informada acrescentando o valor informado ao saldo

**Comment by rubensaraujo** [comment]
Bug: O saldo das contas não estão sendo atualizadas visualmente após o credito ser aplicado

**Comment by rubensaraujo** [comment]
> Bug: O saldo das contas não estão sendo atualizadas visualmente após o credito ser aplicado

Consertado
